### ISSUE TITLE
Non turbo core gets locked to ratio 22 instead of 26

### ISSUE THREAD

**Issue by henr1kas** [psyq321/PowerMonkey#15]
Title.
Basically setup to boot powermonkey before windows it applies undervolt and everything, but when turbo is disabled max ratio is 22 instead of 26 normally for my i7-9750hf

configuration.c: https://pastebin.com/RpWWZvM5

**Comment by 1337heker** [comment]
To reproduce I downloaded ThrottleStop and toggled disable turbo.
