### ISSUE TITLE
How to automatically enter the Windows after booting PowerMonkey.efi instead of returning to the boot selector

### ISSUE THREAD

**Issue by ghost** [psyq321/PowerMonkey#2]

**Comment by BapiGso** [comment]
divide the hard disk into a fat32 partition, and then use these two commands to automatically load at startup
cp fs0:\powermonkey.efi fs1:
bcfg driver add 0 fs1:powermonkey.efi "powermonkey"

**Comment by ssYanhuo** [comment]
I made a simple UEFI application to solve this: https://github.com/ssYanhuo/PowerMonkeyLoader, this can skip the 5 seconds wait of the startup.nsh method.

**Comment by ssYanhuo** [comment]
I made a simple UEFI application to solve this: https://github.com/ssYanhuo/PowerMonkeyLoader

**Comment by e1z0** [comment]
In grub2 it's easy to load efi, one after another, example:

```
menuentry "Windows + Power Monkey" {
        insmod part_gpt
        insmod fat
        search --no-floppy --fs-uuid --set=root PART_UUID
        chainloader /EFI/PowerMonkey/PowerMonkey.efi
        boot
        chainloader /EFI/Microsoft/Boot/bootmgfw.efi
        boot
}
```

You can also preload self signed certificates using mok manager and sign your efi, so it can boot even in secureboot...
