### ISSUE TITLE
Hangs when programming on Acer Predator helios 300 (PH-315-54) TigerLake

### ISSUE THREAD

**Issue by realahnet** [psyq321/PowerMonkey#27]
I recently tried compiling PowerMonkey as the I9 11900H in my laptop overheats alot and i wanted to switch to WSL for doing my compiling tasks. However after Compiling PowerMonkey and booting to shellx64.efi. PowerMonkey starts but then it just hangs there when its right about to program. the caps lock key works for a bit and then just dies and it hangs too. I am forced to reboot afterwards. I tried enabling the logging mode by declaring it as said in the guide but that didnt work either. No logs were shown and it seemed to hang in the exact same way. The settings i edited were Voltage offsets which i set both for core and cache to -60mV. I have confirmed these settings are stable for my laptop as i was daily driving them before with throttlestop i switched to WSL. I hope this is resolvable since Undervolt is badly needed for this laptop. Thanks!

**Comment by trihutama** [comment]
have you check if Point-based V/F Curve Adjustment is disabled?

**Comment by realahnet** [comment]
> have you check if Point-based V/F Curve Adjustment is disabled?

I am not sure but looking at the CONFIGURATION.c file looks like it is. But could you tell me which settings to check for sure?

**Comment by realahnet** [comment]
I am closing this thread since i found a way to unlock advanced bios for this model. And with the overclocking menu i was able to undervolt it inside bios so power monkey isnt needed anymore. But thanks to whoeever replied.
