### ISSUE TITLE
missing CpuDataVR.h

### ISSUE THREAD

**Issue by alanpi** [psyq321/PowerMonkey#5]
Itried to build it with the EDK2 route but iam getting a error

build.py...
/home/alan/src/edk2/MdeModulePkg/Application/PowerMonkeyApp/PowerMonkey.inf(56): error 000E: File/directory not found in workspace
	/home/alan/src/edk2/MdeModulePkg/Application/PowerMonkeyApp/CpuDataVR.h
 

- Failed -

**Comment by psyq321** [comment]
Fixed in: [e954501565803a40198a98b9269dcc02a3f791aa](https://github.com/psyq321/PowerMonkey/tree/e954501565803a40198a98b9269dcc02a3f791aa)
