### ISSUE TITLE
New error in gcc edk2

### ISSUE THREAD

**Issue by alanpi** [psyq321/PowerMonkey#6]
Tried the new build getting a new error ubuntu 21.10 gcc 10

```
/home/alan/src/edk2/MdeModulePkg/Application/PowerMonkeyApp/DelayX86.c:36: error: ignoring ‘#pragma intrinsic ’ [-Werror=unknown-pragmas]
   36 | #pragma intrinsic(__rdtsc)                // At this point, code will look so
      |
/home/alan/src/edk2/MdeModulePkg/Application/PowerMonkeyApp/DelayX86.c:37: error: ignoring ‘#pragma intrinsic ’ [-Werror=unknown-pragmas]
   37 | #pragma intrinsic(_mm_pause)              // fugly that writing it in pure SMM
      |
/home/alan/src/edk2/MdeModulePkg/Application/PowerMonkeyApp/DelayX86.c: In function ‘StallCpu’:
/home/alan/src/edk2/MdeModulePkg/Application/PowerMonkeyApp/DelayX86.c:110:21: error: implicit declaration of function ‘__rdtsc’ [-Werror=implicit-function-declaration]
  110 |   UINT64 endTicks = __rdtsc() + ticks;
      |                     ^~~~~~~

```

**Comment by psyq321** [comment]
Can you temporarily use Clang? 

I will fix the gcc compilation as soon as I can (if I can get this reproduced on WSL2, probably tonight)

**Comment by alanpi** [comment]
where do i have to add `DEBUG_CLANGDWARF_X64_CC_FLAGS         = DEF(CLANG38_ALL_CC_FLAGS) -m64 "-DEFIAPI=__attribute__((ms_abi))" -mno-red-zone -mcmodel=small -fpie -Oz -flto DEF(CLANG38_X64_TARGET) -g
DEBUG_CLANGDWARF_X64_DLINK_FLAGS      = DEF(CLANGDWARF_IA32_X64_DLINK_FLAGS) ``` **` -z notext `** ``` -flto -Wl,-O3 -Wl,-melf_x86_64 -Wl,--oformat,elf64-x86-64 -Wl,-pie -mcmodel=small -Wl,--apply-dynamic-relocs
DEBUG_CLANGDWARF_X64_DLINK2_FLAGS     = DEF(CLANGDWARF_X64_DLINK2_FLAGS) -O3 -fuse-ld=lld

RELEASE_CLANGDWARF_X64_CC_FLAGS       = DEF(CLANG38_ALL_CC_FLAGS) -m64 "-DEFIAPI=__attribute__((ms_abi))" -mno-red-zone -mcmodel=small -fpie -Oz -flto DEF(CLANG38_X64_TARGET)
RELEASE_CLANGDWARF_X64_DLINK_FLAGS    = DEF(CLANGDWARF_IA32_X64_DLINK_FLAGS) -z notext -flto -Wl,-O3 -Wl,-melf_x86_64 -Wl,--oformat,elf64-x86-64 -Wl,-pie -mcmodel=small -Wl,--apply-dynamic-relocs
RELEASE_CLANGDWARF_X64_DLINK2_FLAGS   = DEF(CLANGDWARF_X64_DLINK2_FLAGS) -O3 -fuse-ld=lld

NOOPT_CLANGDWARF_X64_CC_FLAGS         = DEF(CLANG38_ALL_CC_FLAGS) -m64 "-DEFIAPI=__attribute__((ms_abi))" -mno-red-zone -mcmodel=small -fpie -O0 DEF(CLANG38_X64_TARGET) -g
NOOPT_CLANGDWARF_X64_DLINK_FLAGS      = DEF(CLANGDWARF_IA32_X64_DLINK_FLAGS) -z notext -Wl,-O0 -Wl,-melf_x86_64 -Wl,--oformat,elf64-x86-64 -Wl,-pie -mcmodel=small -Wl,--apply-dynamic-relocs
NOOPT_CLANGDWARF_X64_DLINK2_FLAGS     = DEF(CLANGDWARF_X64_DLINK2_FLAGS) -O0 -fuse-ld=lld
` ?
Ill tried to compile with it but iam getting errors.
iam using this command `sudo build -p MdeModulePkg/MdeModulePkg.dsc -t CLANGDWARF -a X64
`

**Comment by psyq321** [comment]
Here are my target.txt, tools_def.txt, and build_rule.txt files.

EDK2 repo was fetched yesterday (master branch) 

[build_rule.txt](https://github.com/psyq321/PowerMonkey/files/7858559/build_rule.txt)
[target.txt](https://github.com/psyq321/PowerMonkey/files/7858560/target.txt)
[tools_def.txt](https://github.com/psyq321/PowerMonkey/files/7858561/tools_def.txt)

**Comment by alanpi** [comment]
dosent work for me i cant compile anything. ill wait until you fix it. iam using nativ ubuntu installation not wsl2

**Comment by psyq321** [comment]
I fixed gcc compilation - it is in the repository now (v0.2.0)

I used "GCC5" toolchain definition in EDK2

**Comment by Charlyo** [comment]
which gcc version are you guys using?

**Comment by alanpi** [comment]
Smaller than 11 with the newest version their is a problem with brotli. You can use Ubuntu 16.04 or 21.10 an downgrade to gcc10

**Comment by psyq321** [comment]
Ah... I only had WSL2 system last night that was not specced right.

I will test gcc 11 on my Arch rig tonight.

**Comment by alanpi** [comment]
> Ah... I only had WSL2 system last night that was not specced right.
> 
> I will test gcc 11 on my Arch rig tonight.

I replied to a question of charlyo but he deleted his comment. I didn't tested the new build yet

**Comment by Charlyo** [comment]
I use gcc9 inside wsl as well. However I'm still having issues at the linking stage.

**Comment by psyq321** [comment]
@Charlyo - can you please attach the dump of the console output when the linker throws an error? Thanks!

**Comment by Charlyo** [comment]
Magically after a restart, build worker and it created the PowerMonkey.efi inside Build/MdeModule/DEBUG_GCC5/X64 folder. No clue on the linking errors 🤷🏼
