### ISSUE TITLE
Issue WSL, Sandbox, Virtual Machine, Hypervisor Platform

### ISSUE THREAD

**Issue by jang5th** [psyq321/PowerMonkey#9]
I created powermonkey.efi successfully with parameter:
Core: -160mV
Ring (Cache): -80mV
Intel GPU: -40mV
iGPU Unslice: -40mV

In BIOS 10875h
Secure Boot: Disable
Virtual: Enable

Everything is ok before I install components: WSL, Sandbox, Virtual Machine, Hypervisor Platform.
Windows 11 restricted undervolt.

Please help.

**Comment by Nystrata** [comment]
How are you checking your undervolt with PowerMonkey?
PowerMonkey can still be used with Windows 11 with virtualization - however you won't see undervolt values in ThrottleStop or HWinfo
